### ISSUE TITLE
Invalid licenses in node_modules

### ISSUE THREAD

**Issue by RaviVaranasi** [romefrontend/rome#1037]
I'm seeing linting error even though `node_modules` is in lint.ignore section

`rome.json` in `.config`
```
// For configuration documentation see http://romefrontend.dev/#project-configuration
name: "rome-poc"
root: true
lint: {
    ignore: ["node_modules/**"]
    
}
```

Run `rome check`
```
node_modules/pouchdb-collections/package.json:44:14 parse/spdxLicense ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ Unknown SPDX license Apache

  ℹ Did you mean Apache-1.0?

  - Apache
  + Apache-1.0

  ℹ Or one of these?

  - Apache-1.1
  - Apache-2.0
```

**Comment by sebmck** [comment]
We "lint" package.json files but it’s not really linting. We load, normalize, and validate any we see during project initialization since they’re required for module resolution.

It has been an area of confusion though because you cannot ignore them because any validation errors are either legitimate problems or bugs/unhandled validation cases, and are fatal.

**Comment by mrewers** [comment]
So what is the resolution here? I'm not sure it's reasonable to expect that people only use dependencies that have a valid license in the package.json since that is largely out of their control.

**Comment by sebmck** [comment]
Probably a project config option to allow certain invalid licenses.

**Comment by RaviVaranasi** [comment]
FYI: this is a template generated with expo to generate a `react-native` application.

**Comment by ematipico** [comment]
Next release will have a new configuration space where to store these invalid licenses
