### ISSUE TITLE
Ban nested ternary (from list in discord)

### ISSUE THREAD

**Issue by macovedj** [romefrontend/rome#746]
Is the thought here to ban all nested ternaries, or simply those that don't include parentheses to disambiguate.  I'm a little rusty on this, but I guess you could probably use some DeMorgansesqe logic to convert nested ifs into an or or something?  If so, do we want to ban nested ifs too?  I think I remember from my logic classes that "if p then q" is logically equivalent to "!p or q", but I'm not sure how well formal logic translates to javascript.  If there's not something logically equivalent, then are we concerned at all about limiting the logic that the code is capable of executing?

**Comment by bitpshr** [comment]
I thought the intention of this rule was to ban nested ternaries purely because of poor readability. They can always be broken up into either separate ternaries or traditional `if` statements, so I don't think an autofix would ever limit application logic.

Note that the rule implementation by @VictorHom is at https://github.com/romefrontend/rome/pull/725.
