### ISSUE TITLE
💭 Shorthand CLI flags

### ISSUE THREAD

**Issue by noftaly** [romefrontend/rome#963]
Hey!

I've juste installed Rome and wanted to get the help page: my first reflex was to type `rome -h` in the terminal. Unfortunately, like all the other flags in Rome, there is no shortcut. It would've been great if there was something like `-h` for `--help`, `-v` for `--version` etc etc, for every or most of the Rome flags.

I would've love to make a PR for that but Rome uses its own argument parsing library and I don't have the time to see how it works.

**Comment by sebmck** [comment]
Thanks for the suggestion! We actually already have support for parsing shorthand flags. The error is actually after the fact. I have generally found shorthand flags to be extremely vague and confusing. ie. would `rome -v` dump the version, or start Rome in verbose mode? I'll leave this issue open for discussion but it was a deliberate choice to leave them unsupported.

**Comment by bitpshr** [comment]
I feel like we should continue to implicitly not shorthand flags since they really are vague, but I feel like special-casing `-h` specifically may be a good idea. It's almost pseudo-standard, and it will be useful for users who do expect shorthand flags since that command will in turn show them that no other commands have them.

**Comment by sebmck** [comment]
That sounds good! We can also provide a suggestion for `-v`. We used to have a `--verbose` flag but no longer do. Regardless, we could still check if there's been a `verbose` flag declared and hint at it too. So far we've been making all the Rome packages very general without being constrained too much by Rome uses, so it'd be really nice to open them up in the long distant future since I think a lot of them are better than the existing solutions.
